### ISSUE TITLE
index is getting too big

### ISSUE THREAD

**Issue by idokin** [klvs/fbspy#12]
We need to breakup index.html into JS files and maybe a css file.

**Comment by klvs** [comment]
So there are options here... Once you want to modularize your js you can run into issues. Nowadays people use module loaders like webpack, gulp, requirejs, etc. They allow you to do things like var foo = require(‘./bar.js’) We can discuss if this is necessary as it’s a lot of overhead. I could probably set it up in under 90mins but it’s a more advanced workflow for sure.

Also, sorry I haven’t been able to work on this today. I’ll make a solid push tomorrow. Thanks for your hard work @idokin

**Comment by idokin** [comment]
no worries, I'm having fun.

**Comment by klvs** [comment]
Dope man. Just keep crushing those issues in that case.
