### ISSUE TITLE
Fix line tracker label and add to smaller graphs

### ISSUE THREAD

**Issue by idokin** [klvs/fbspy#13]

**Comment by idokin** [comment]
@klvs @bodeyp1234  Where do you think the label for the trackers should go, following the line or static somewhere? maybe on the future control panel?

**Comment by idokin** [comment]
@klvs @bodeyp1234  any input?

**Comment by klvs** [comment]
I think the line tracker come secondary to zoom. idk if decided to ditch that for now. Zoom pan would be cool if we can do that. Also I the current one seems kinda laggy.

**Comment by idokin** [comment]
agreed, but zoom is hard af...I'll look into zoom tonight after I study for a few hours

**Comment by bodeyprovansal** [comment]
Agree with Alex about the zoom. But I think having the labels follow the trackers would be more user friendly, especially with such a large graph. You want people's eyes jumping around the screen as little as possible.
