### ISSUE TITLE
Idea regarding mini graphs

### ISSUE THREAD

**Issue by idokin** [klvs/fbspy#22]
So instead of 4 mini graphs have 1 big graph that changes based on which day you click on in the other main graph and allows you to see it to the full extent...or something along those lines. anything just not literally a replica broken into 4, I don't think that makes sense.
What do you guys think?
@klvs @bodeyp1234

**Comment by klvs** [comment]
I think the idea is to have the 4 mini graphs be displaying the different categories of users. The status quo is just place holders for that data.

**Comment by idokin** [comment]
right but isn't the three buttons do the same?

**Comment by klvs** [comment]
@ido three buttons?

**Comment by idokin** [comment]
check master

**Comment by idokin** [comment]
--continue discussion on slcak anyhow
