### ISSUE TITLE
Needs Zoom

### ISSUE THREAD

**Issue by klvs** [klvs/fbspy#3]
We should add a zoom capability to the large viz.

**Comment by bodeyprovansal** [comment]
Update: I got a zoom working that zooms in and out when the mouse is over part of the svg, which is any point on the graph or axis of the graph. Problem is I'm guessing the space in between the points doesn't count as part of the svg. I'll push when I get that worked out.

**Comment by klvs** [comment]
Try this. I had the same problem in the last project. http://stackoverflow.com/questions/16108471/d3-js-zooming-only-works-when-cursor-over-pixels-of-graph http://stackoverflow.com/questions/16108471/d3-js-zooming-only-works-when-cursor-over-pixels-of-graph

**Comment by bodeyprovansal** [comment]
Sweet, that worked. I tried it a few times and there was a bug once where it stopped drawing the y-axis after zooming, but I couldn't get it to happen again. Might just be my janky trackpad so it should be fine.

**Comment by klvs** [comment]
Zooming is weird in d3. Honestly that solution seems hacky to me. It basically overlays a layer that intercepts zoom events.

Thanks for taking care of it.

**Comment by idokin** [comment]
--working on it in zoom bug issue

**Comment by klvs** [comment]
Wait don’t close it if it’s not fixed in master.

**Comment by idokin** [comment]
Its not fixed but we already have an iaaue for bug
