### ISSUE TITLE
Add smaller day-by-day view

### ISSUE THREAD

**Issue by klvs** [klvs/fbspy#4]
See klvs.github.io the one broken into day1 day2 day3 etc

**Comment by klvs** [comment]
Just like this. Creative liberty appreciated 
![altview](https://cloud.githubusercontent.com/assets/5811023/15666502/f49b39e4-26c5-11e6-8bb5-63f51e906c53.png)

**Comment by klvs** [comment]
Until the capture is finished we can use the current data. If anyone wants to get to it before I'm done generating the sorted datasets they can just use the current data in its unsorted form. It won't look sorted, but the sorted data will be a drop in replacement once it's done.

**Comment by idokin** [comment]
Done. creative work needed + interactivity with the main graph, separate issues though.

**Comment by klvs** [comment]
Lookin’ good. Just checked out your branch. Did you have it working w/ final.csv or just as templates. Good progress either way.

**Comment by idokin** [comment]
Final.csv
