### ISSUE TITLE
Convert survey data to fit current data model

### ISSUE THREAD

**Issue by klvs** [klvs/fbspy#5]
So we had people report when they woke up and when they went to bed on the same day that did the initial collection. We have 30ish responses that need to be converted to fit our data model.

i.e index, time1, time2

For index just use their name (with no spaces) and I'll figure it out.

Time1 and time2 need to me unix time stamps

[When did you sleep-.csv (1).zip](https://github.com/klvs/fbspy/files/290245/When.did.you.sleep-.csv.1.zip)

**Comment by idokin** [comment]
So I was thinking we should have the data compared to the original capture, the reason why I'm trying to figure this out is that I want time1 and time2 to be calibrated to the date so it graphs properly. let me know what day/month you think this times should be at

**Comment by idokin** [comment]
@klvs

**Comment by klvs** [comment]
@idokin I believe the date in the timestamp column is what it should be. We are going to have to compare it to the original capture for this reason. That's okay though.

**Comment by idokin** [comment]
Okay all done,I got all the macros set up so if you want to change the start/end date let me know.
