### ISSUE TITLE
Axis line tracker

### ISSUE THREAD

**Issue by klvs** [klvs/fbspy#8]
Show tool-tip on each axis with the value @ of the current x and y of the mouse. Please comment if this doesn't make sense. Comment if it does too for that matter.

**Comment by idokin** [comment]
MAKES SENSE, ON IT.

**Comment by idokin** [comment]
@klvs @bodeyp1234 I added the line tracker, it still need more css design, but I'm a bad artists, so help me out. I also didn't add the tracking on the Y of the mouse, we should discuss how we want this to work.

**Comment by klvs** [comment]
Leave the CSS up to me unless you can do it fast. If you’ve finished something and it needs some TLC tag me in it or create a new issue. So long as the functionality is there (and it supports HTML) and only need a little styling I can take care of it. CSS is nuanced as fuck and as much as I hate it, I’ve written a lot of it.
