### ISSUE TITLE
Make axis domain adjust to proper data range

### ISSUE THREAD

**Issue by klvs** [klvs/fbspy#9]
We need to make these flush with the axis. It shoudn't be hardcoded because we'll just need to do it again once we have multiple days worth of data. There's a function d3.max (ithinkorsomethinglikethat) that does just this. 
<img width="795" alt="screen shot 2016-05-31 at 12 18 54 am" src="https://cloud.githubusercontent.com/assets/5811023/15666384/755e79a2-26c5-11e6-8332-30054e6f36e9.png">

**Comment by idokin** [comment]
question: is final.csv proper data, all the lines seem really short...

**Comment by klvs** [comment]
Yeah it’s as good as it’s going to get for now. I realized that most of the data doesn’t have a ton of consecutive ‘on’s. There are still advantages to having it this way, but I might have thought twice about leading us down this path if I’d know that.

**Comment by idokin** [comment]
I think we can probably merge a lot of those line, some have short distances between them.

**Comment by klvs** [comment]
Okay, I can look into it. It’s not a super easy problem to solve but it’s def doable.
